dev:
  propel:
    param:
      classname:  DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO

all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=lunitius_tinylittlenotes;host=localhost
      username:   lunitius_tln
      password:   Oicu812!
      encoding:   utf8
      persistent: true
      pooling:    true
